### ISSUE TITLE
TypeError after updating true-myth to 9.3.0 due to loupe/chai inspect conflict

### ISSUE THREAD

**Issue by tkreis** [true-myth/true-myth#1217]
After updating true-myth, my pipeline is failing with:

`TypeError: fn is not a function`

Root cause:
This is caused by [loupe's inspection logic](https://github.com/chaijs/loupe/blob/3ed5f5f4dc636bb39d2b9e42ca681cc03c39a22e/src/index.ts#L96): 
```
("inspect" in value && typeof value.inspect === "function") {
  return value.inspect(options.depth, options);
}
```

true-myth 9.3.0 added an inspect function, but its signature is incompatible with what loupe expects.

Workaround:
Use Node's native assert module instead of chai assertions for example.

**Comment by chriskrycho** [comment]
Thanks for filing this. It’ll be good for other folks who hit it! Loupe is misbehaving here in my view—lots of other libraries might have `inspect` functions in them, after all!—so I definitely won’t be changing this. Again, though, very grateful that you filed it for anyone else who hits it!

**Comment by chriskrycho** [comment]
@tkreis would you be so kind as to open an issue on Loupe so that they know it’s a thing they need to fix?
