### ISSUE TITLE
5.1.1 regression: type inference for Result.ok

### ISSUE THREAD

**Issue by krivachy** [true-myth/true-myth#268]
After updating from 5.1.0 to 5.1.1 we noticed a regression with Typescript not correctly inferring the types when we had `Maybe.nothing()` inside a `Result.ok()`. I've put together a minimal example to illustrate this:

**5.1.1**:

```typescript
import { Maybe, Result } from 'true-myth';

function test(): Result<Maybe<string>, Error> {
  // The following doesn't typecheck
  return Result.ok(Maybe.nothing());
}
```

```
test.ts:7:3 - error TS2322: Type 'Result<Maybe<unknown>, Error>' is not assignable to type 'Result<Maybe<string>, Error>'.
  Type 'Ok<Maybe<unknown>, Error>' is not assignable to type 'Result<Maybe<string>, Error>'.
    Type 'Ok<Maybe<unknown>, Error>' is not assignable to type 'Ok<Maybe<string>, Error>'.
      Type 'Maybe<unknown>' is not assignable to type 'Maybe<string>'.
        Type 'Just<unknown>' is not assignable to type 'Maybe<string>'.
          Type 'Just<unknown>' is not assignable to type 'Just<string>'.
            Type 'unknown' is not assignable to type 'string'.

7   return Result.ok(Maybe.nothing());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The workaround is to specify the type explicitly:

```typescript
return Result.ok(Maybe.nothing<string>());
```

**5.1.0** typechecks perfectly fine:

![image](https://user-images.githubusercontent.com/5367669/146525145-ef794308-c12f-471d-b4a6-dd3dbdfd5fa8.png)

**Comment by chriskrycho** [comment]
This is the knock-on effect of the work I did to fix the regression ID'd in your previous issue, unfortunately, and I have yet to figure out a way to make it pipe the inference through in this scenario while also explicitly handling `null` and `undefined` as inputs to produce `Result<Unit, E>` or `Result<T, Unit>` automatically. I will try to revisit it sometime next week, though.

**Comment by chriskrycho** [comment]
My current approach here, as seen in #273, is to just revert the handling for `null` and `undefined`. This loses some type safety: these type check now.

```ts
// Result<null, unknown>
let heavySigh = Result.ok(null);

// Result<unknown, undefined>
let deeplySad = Result.err(undefined);
```

Fundamentally, the overload-driven resolution currently used doesn't correctly pass through the type parameters all the way, and I haven't found a way to resolve it. I will see if we can make it work for 6.0, or possibly a 5.2 release if I can get it sorted in a backwards-compatible way.

**Comment by chriskrycho** [comment]
Notably, the underlying error that actually surfaced this is a *super* weird condition: for some reason, TS was not following its normal resolution path, where an otherwise unconstrained type parameter occurring in a return statement ends up inferred as the type specified by the function return parameter. I have, off the top of my head, no idea why. 🙃

**Comment by chriskrycho** [comment]
Fix released in v5.1.2.
