### ISSUE TITLE
Typescript 3.6 "type is not assignable" error

### ISSUE THREAD

**Issue by fcoelho** [true-myth/true-myth#54]
Hi, I'm having an issue using `mapOr` and `mapOrElse` in TS 3.6. I'm using the latest version of `true-myth`. Consider the following program:

```typescript
import { Maybe } from 'true-myth';

const len = (s: string) => s.length;

const val = Maybe.of("42");
const out = Maybe.mapOr(0, len, val);

console.log(val);
console.log(out);
```

This works with TS up to 3.5.3 but fails in 3.6 with the following error:

```
main.ts:6:28 - error TS2345: Argument of type '(s: string) => number' is not assignable to parameter of type '(t: string) => 0'.
  Type 'number' is not assignable to type '0'.

6 const out = Maybe.mapOr(0, len, val);
                             ~~~


Found 1 error.
```

One way to overcome this is to specify types explicitly, but I'd like to avoid it if possible:

```
const out = Maybe.mapOr<string, number>(0, len, val);
```

**Comment by chriskrycho** [comment]
Thank you for reporting this! I noticed the same thing, but I haven't actually come up with a good solution yet—because I haven't figured out why it's treating the type as a constant instead of widening it like it normally would! If you happen to end up having time to figure out *why* it's narrowing to a `const` type here, that'd be amazing. The more so because [this is still broken on TS 3.7 Beta](https://www.typescriptlang.org/play/?ts=3.7-Beta#code/JYWwDg9gTgLgBAbzgWQIYE8BGBTOBfOAMyghDgHIYoBXbAWhHRgAtyBuAWAChuBjCAHYBneABtsAuAF44ACiEAuOCKjABAcwCU0gHzKAdOI0tOPLv2HwAbqlHSUGHPoiFZAIgAsAJjebTFkTgIangZNCxsfRBUMAB5KFkABgAaOCNUm1E-bj5BIQhxQwh1WUzs8zyCyNFi2WCYPyA).

(Aside: how cool is it that you can test stuff like this in the playground now? 🤩)

**Comment by chriskrycho** [comment]
A bit of digging indicates that this is specifically to do with the way that we're using `NonNullable<U>` in the return position of a number of cases.

Here's a fairly minimal reproduction of the problem, with just `mapOr` and the things it directly depends on: [reproduction]. And here's a fix which is identical *except* in removing `NonNullable` on these return types: [fix]. Somehow – I don't yet know how or why! – this is triggering TS's narrowing-to-`const` mechanics, which tightened in 3.6 a little bit.

(When you write `const foo = 'bar'`, TS now defaults to typing that as `foo: 'bar'` *not* `foo: string`. This is usually fine because `'bar'` is narrower than `string` and so can be passed wherever `string` is required. However, in this case it's combining with the `NonNullable` so that the generic type ends up being the constant value instead of the wider value.)

[reproduction]: https://www.typescriptlang.org/play/?ssl=18&ssc=4&pln=14&pc=4#code/MYGwhgzhAEBSCuEAuAeAKgPmgbwFDWgCcBTMAEwHsA7EAT2gDcwR5iAuaNAbl32mGrJC8YEgqEAFExbEA-BzTQAPtCrwQIAJQ4+BAJYAzaFOatoAXnOr1WnQXvQkAC0IUA7quIeAooVeSAIgA5AHkwkIAFbwDNHgcAX14HZz0IADppMytM4jjoRL5kMCQ9YGgKAxQAQQwTGQ4qzQ4AWTBaACNiaqw8BxIkeEIqTw8EZDrWWL4CggBbMAAHEMIUAFVasmIDMHUkADVTdmhVgBp+do4JJAVtcywg6iCbMHaQLvWm47t7fsHh4HaVycqQyhymBBm0FSYyQEk+KRgqTgiFQmG+BF+Q0cwly0ySUIgDxSVAA5nCOAiCdAicDSegeroiMQBljtiAILiIbgCm8kNSQmgABIASSCAHEODS9HSwFRaBgeLhQJAYFK6WjevxBEhhKJxBM5AplNYNNpNfojAboABCKxqU3o+zOVweKheaC+fwSAIATXCITOoX9MUZkItxlCQtFYosdpsZsZBEjIvFFkcwIgeS5jMxw2T0bykPmSxW6wkm22uwO9WOZwBl2unFu90ez1e7wwn1Wjtz0GLy3LWx2IH2hzr7TOCPB+Xx0JR5PTSKRMPpPeZf2gbI5hdnhIoxLJ8IzVLVJNX5qZLOGOtYO4KxAAHgtxHyDPAqKI9NQ+4tlugzmW4irBwpw-gsABiVANjcFgtlQTwaC8bxrBgZzzB0RytBh9Jdjwj7PoQr7vp+379isaAAbUQEgWhiyQdBTawdSraIe2KGfBI6GdC0bSdDhTGrHhT4vpuxElKRv7kZREjUccHHFvRxiNmgzbMfBbbIR8TGcbxmG6fxdzHEJBFER+4nDGR-7HLUfCyacfAKVQ8hKTBhn2XMunOVhfGYLgXbGhIOkYTx2GYKpqzaCogWOQxKlMQ86msZpnbaVxemhSlbkJgQb5mV+wxvhoIQLBIBhQS5jFuWhIU+SlF69rMaRzuM2iyJuVCcaCMjaBwQE7nwuUkcMCxgIRejMMVpXlVcrlYBFlxpTVXRhQJeSDeZ0AjWNE0lWVsXhXWgyEHoxBkN56W1bhA1iflm2jSUO1TftAmHX4J1nZ5S04SBAVBdx0DnQZc3ZT865YsAR3vedNqWNA74VtKp2JtAbWFSAk1la9x2nedmjI5cj46mAADCkM47pX0rYZaMY1QZyE4QJNkx9GHTpCDV0cMlhWPDWyI2QjJtVtD3owsjIcGlsY81QCNugLDhC-d42izpEFUHjDgcMLyuTY5tGszwBRILQCzEAD+lolYK5oiop70jwAhUMg5sYWmmoVBw9IGjclNYIZOQwyaIAo8iyBpBUBo9fyUbiic3K8I7ztgGm53hwYEgAORIMUxCEBAGdTInfIVsOSAADLEFz0AAAwO9q0BvFXEgQBwQjSiSqnpI3JLOHXTt8u0aZgGkZGDpWI4V3TDeV1MQA
[fix]: https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=93&pc=1#code/MYGwhgzhAEBSCuEAuAeAKgPmgbwFDWgCcBTMAEwHsA7EAT2gDcwR5iAuaNAbl32mGrJC8YEgqEAFExbEA-BzTQAPtCrwQIAJQ4+BAJYAzaFOatoAXnOr1WnQXvQkAC0IUA7quIeAooVeSAIgA5AHkwkIAFbwDNHgcAX14HZz0IADppMytM4jjoRL5kMCQ9YGgKAxQAQQwTGQ4qzQ4AWTBaACNiaqw8BxIkeEIqTw8EZDrWWL4CggBbMAAHEMIUAFVasmIDMHUkADVTdmhVgBp+do4JJAVtcyxVpuO7e37B4eB2q6dUjMOpghm0FSYyQEkeKRgqTgiFQmGeBFeQ0cwly0ySQIgQQoKSoAHMwRwIRjoFicbj0D1dERiAMkdsQBBUQDcAUQDSSSE0AAJACSQQA4hxSd88SgwFRaBgeLhQJAYMK9KK4b1+IIkMJROIJnIFMprBptCr9EZtdAAIRWNQG+H2ZyuDxULzQXz+CQBACa4RCZ1CXpiVMBxuMoW5fP5FktNkNVIIId5Aosjm+EDyzKpiOGcbDeUB8yWK3WEk2212B3qxzOH0u104t3uj1WNoz0DzyyLWx2IH2h0r7TOEP++XRwJhBKTUKhIIpTZpb2g9MZOeHmOxIvx4OTxIVSspfVnSPVrCXBWIAA8FuIkPP4FRRHpqC3Fst0GdC+JVhxTo+FgAxKjVm4LHuM55g6I5WjAikGx4M8L0IK8DBvO8H1bFY0FfWp30-EDFj-ADayA45HgkUDOhaNpOigwjVhg89L2vW8ShQp80IwiQsKIy48zw4wazQOsiMIkiKPAkSqLuY5aLghCkKY4ZUJfY5aj4DjTj4biqHkXjAIktS5hErSIMozBcAbPUJGEsDyMgzABIeczhN-f9tII3SBMssjoCMrpbOo6MCEQxj72GRCNBCBYJAMZyrh04CW2s4yMH8l593ktIR3GbRZHnKgSN+GRtA4d8lz4QLkOGBYwHgvRmHCyLor4uziNI0SbKS6i8jKuToEq6raoiqL8P46jK0GQg9GIMhvISnyks-TrZOCnqqpKfr6qGuzRr8CapoMmaoM-ByWv23y3JnWl3jGnbvPNSxoBvYtFUmmNoGy0KQDqqKtvGybvM0F7LjPdUwAAYSu36RJO9qJPez6qDOIHCFB8HdrAwdAWbDSIysB6tiesgqWy3rVo+hYqQ4FrsfuqhHsdAmHCJlaatJxy-3+hwOGJ5m6o0nC0Z4AokFoBZiC8sS4SsKc4RUbdyUwHgBCoZAxbAxMVQqDgKW1G4ocInJbv1EBXuhZA0gqbVCo5UMBROFleEV5WwETbyzYMCQAHIkGKYhCAgd2pgdq9i07JAABliGGKwAAYFbVaA2Uj4wIA4IRFVxAT0gT3FnFjpWr3aRMwDSVD2xLLtw-h+OI6mIA

**Comment by chriskrycho** [comment]
Will fix this in the next major release, coming probably tomorrow. Unfortunately, I haven't come up with a good workaround the preserves the use of `NonNullable` constraints on these. I will probably play some more tomorrow before committing to that, but at a minimum I want to unblock use of the library with 3.6+.
