### ISSUE TITLE
Module '"./utils"' has no exported member '_Brand'

### ISSUE THREAD

**Issue by strmer15** [true-myth/true-myth#96]
When I upgraded our application from 4.0.0 to the 4.1.0 version of true-myth, my Typescript (4.1.3) project fails to build with `tsc`.

```
$ tsc --build
../../node_modules/true-myth/unit.d.ts:1:10 - error TS2305: Module '"./utils"' has no exported member '_Brand'.

1 import { _Brand } from './utils';
           ~~~~~~
```

In my `node_modules/true-myth/unit.d.ts` file:

```
import { _Brand } from './utils';
/**
  The `Unit` type exists for the cases where you want a type-safe equivalent of
  `undefined` or `null`. It's a concrete instance, which won't blow up on you,
  and you can safely use it with e.g. [`Result`](../modules/_result_.html)
  without being concerned that you'll accidentally introduce `null` or
  `undefined` back into your application.
 */
export declare const Unit: _Brand<"unit">;
export declare type Unit = typeof Unit;
export default Unit;
//# sourceMappingURL=unit.d.ts.map
```

In `node_modules/true-myth/utils.d.ts`:
```
/** @internal */
export {};
//# sourceMappingURL=utils.d.ts.map
```

When I look at the 4.0.0 version, `unit.d.ts` is the same, but utils.d.ts contains:
```
/**
 * Check if the value here is an all-consuming monstrosity which will consume
 * everything in its transdimensional rage. A.k.a. `null` or `undefined`.
 */
export declare const isVoid: (value: any) => value is null | undefined;
export declare function curry1<T, U>(op: (t: T) => U, item?: T): U | ((t: T) => U);
export declare type AndThenAliases = 'andThen' | 'chain' | 'flatMap';
export declare class _Brand<Tag extends string> {
    private _brand;
    constructor(t: Tag);
}
//# sourceMappingURL=utils.d.ts.map
```

**Comment by chriskrycho** [comment]
First, thanks for opening this issue! Second: hmm, this is odd. The change may be [here](https://github.com/true-myth/true-myth/commit/e68d77c143a98273e21d2ff25747ee3fe9036870#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351); there we set the `stripInternal` flag to `true`, which would have this effect. I'm surprised it hasn't come up before! I'll cut a bug fix change later today that reverts the `stripInternal` bit (and make sure it does the right thing for both docs and types as published)!

**Comment by chriskrycho** [comment]
Update: we *already* had `stripInternal: true` (and shouldn't have!); the problem was that this was the first time we *added* `@internal` annotations. I've opened #97 to fix this, and will cut 4.1.1 with it!

**Comment by strmer15** [comment]
Thanks for the quick fix @chriskrycho ! I've verified that 4.1.1 fixes the problem for us.

**Comment by chriskrycho** [comment]
Excellent, and thanks for confirming!
