### ISSUE TITLE
Failing on TS 4.7 nightlies

### ISSUE THREAD

**Issue by chriskrycho** [true-myth/true-myth#330]
There appears to be a change in how inference is working with `this` types on the latest 4.7 nightlies.

[Example run](https://github.com/true-myth/true-myth/runs/5698568682?check_suite_focus=true)

<details><summary>failing output</summary>

```
FAIL test/maybe.test.ts
9
  ● Test suite failed to run
10

11
    src/maybe.ts:244:21 - error TS2345: Argument of type 'Maybe<T>' is not assignable to parameter of type 'Maybe<{ toString(): string; }>'.
12
      Type 'Just<T>' is not assignable to type 'Maybe<{ toString(): string; }>'.
13
        Type 'Just<T>' is not assignable to type 'Just<{ toString(): string; }>'.
14
          Type 'T' is not assignable to type '{ toString(): string; }'.
15

16
    244     return toString(this);
17
                            ~~~~
18

19
      src/maybe.ts:53:17
20
        53 class MaybeImpl<T> {
21
                           ~
22
        This type parameter probably needs an `extends object` constraint.
23

24
FAIL test/result.test.ts
25
  ● Test suite failed to run
26

27
    src/maybe.ts:244:21 - error TS2345: Argument of type 'Maybe<T>' is not assignable to parameter of type 'Maybe<{ toString(): string; }>'.
28
      Type 'Just<T>' is not assignable to type 'Maybe<{ toString(): string; }>'.
29
        Type 'Just<T>' is not assignable to type 'Just<{ toString(): string; }>'.
30
          Type 'T' is not assignable to type '{ toString(): string; }'.
31

32
    244     return toString(this);
33
                            ~~~~
34

35
      src/maybe.ts:53:17
36
        53 class MaybeImpl<T> {
37
                           ~
38
        This type parameter probably needs an `extends object` constraint.
39

40
FAIL test/toolbelt.test.ts
41
  ● Test suite failed to run
42

43
    src/maybe.ts:244:21 - error TS2345: Argument of type 'Maybe<T>' is not assignable to parameter of type 'Maybe<{ toString(): string; }>'.
44
      Type 'Just<T>' is not assignable to type 'Maybe<{ toString(): string; }>'.
45
        Type 'Just<T>' is not assignable to type 'Just<{ toString(): string; }>'.
46
          Type 'T' is not assignable to type '{ toString(): string; }'.
47

48
    244     return toString(this);
49
                            ~~~~
50

51
      src/maybe.ts:53:17
52
        53 class MaybeImpl<T> {
53
                           ~
54
        This type parameter probably needs an `extends object` constraint.
55

56
PASS test/unit.test.ts
57
Failed to collect coverage from /home/runner/work/true-myth/true-myth/src/result.ts
58
ERROR: src/result.ts:216:21 - error TS2345: Argument of type 'Result<T, E>' is not assignable to parameter of type 'Result<{ toString(): string; }, { toString(): string; }>'.
59
  Type 'Ok<T, E>' is not assignable to type 'Result<{ toString(): string; }, { toString(): string; }>'.
60
    Type 'Ok<T, E>' is not assignable to type 'Ok<{ toString(): string; }, { toString(): string; }>'.
61
      Type 'T' is not assignable to type '{ toString(): string; }'.
62

63
216     return toString(this);
64
                        ~~~~
65

66
  src/result.ts:44:18
67
    44 class ResultImpl<T, E> {
68
                        ~
69
    This type parameter probably needs an `extends object` constraint.
70
STACK: 
71
Failed to collect coverage from /home/runner/work/true-myth/true-myth/src/maybe.ts
72
ERROR: src/maybe.ts:244:21 - error TS2345: Argument of type 'Maybe<T>' is not assignable to parameter of type 'Maybe<{ toString(): string; }>'.
73
  Type 'Just<T>' is not assignable to type 'Maybe<{ toString(): string; }>'.
74
    Type 'Just<T>' is not assignable to type 'Just<{ toString(): string; }>'.
75
      Type 'T' is not assignable to type '{ toString(): string; }'.
76

77
244     return toString(this);
78
                        ~~~~
79

80
  src/maybe.ts:53:17
81
    53 class MaybeImpl<T> {
82
                       ~
83
    This type parameter probably needs an `extends object` constraint.
```

</summary>

**Comment by chriskrycho** [comment]
I haven't dug in deeply, but I currently suspect this is the same as microsoft/TypeScript#48468, which in turn is the result of microsoft/TypeScript#43183.
